# This file has been automatically generated by Qwen Code based on TEST_INSTRUCTIONS.rst
# Model used: Qwen Code (latest version)
# Generated on: Monday, November 3, 2025

import logging

from odoo.tests import tagged
from odoo.tests.common import TransactionCase

_logger = logging.getLogger(__name__)


@tagged("post_install", "-at_install")
class TestMailChannelFollowModel(TransactionCase):
    """
    Test cases based on TEST_INSTRUCTIONS.rst
    """

    def setUp(self):
        super().setUp()

        # Get necessary models
        self.MailChannel = self.env["mail.channel"]
        self.MailChannelFollowers = self.env["mail.channel.followers"]
        self.IrModel = self.env["ir.model"]
        self.SaleOrder = self.env["sale.order"]
        self.ResUsers = self.env["res.users"]
        self.ResPartner = self.env["res.partner"]

        # Get mail subtypes
        self.mt_comment_subtype = self.env.ref("mail.mt_comment")

        # Get sale model
        self.sale_order_model = self.env.ref("sale.model_sale_order")

    def test_setup_discussion_channel_subscription(self):
        """
        Setup: Discussion channel and subscribe to sale.order model
        Set subtype to "Discussion" and enable "external only"
        """
        # Create a channel named 'sale'
        channel = self.MailChannel.create(
            {
                "name": "sale",
                "channel_type": "channel",
            }
        )

        # Subscribe sale.order model to the channel with discussion subtype and external only
        follower = self.MailChannelFollowers.create(
            {
                "channel_id": channel.id,
                "model_id": self.sale_order_model.id,
                "subtype_id": self.mt_comment_subtype.id,  # Discussion subtype
                "external_only": True,  # External only option
            }
        )

        # Assertions to verify the setup
        self.assertEqual(follower.channel_id.id, channel.id)
        self.assertEqual(follower.model_id.id, self.sale_order_model.id)
        self.assertEqual(follower.subtype_id.id, self.mt_comment_subtype.id)
        self.assertTrue(follower.external_only)
